# input-files: [*.md]
input-file: output/manuscript.md
reference-doc: /Users/hwo/gh/devdocs/hwo-academicTempl/templates/propuesta-reference.docx
log-file: output/docdoctec.log
output-file: output/docdoctec-${TRIGGERING_SHA_7}.docx
to: docx
