# input-files: [article.md]
# input-file: ./contd/doc/*.md
reference-doc: /home/runner/hwo-academicTempl/templates/rmd-myriad-minion-reference.docx
log-file: output/docdoctec.log
output-file: output/docdoctec.docx
to: docx
