# input-files: [article.md]
# input-file: ./contd/doc/*.md
reference-doc: /home/vscode/hwo-academicTempl/templates/rmd-myriad-minion-reference.docx
log-file: output/docpropuesta.log
output-file: output/docpropuesta.docx
to: docx
