# input-files: [presentation.md]
log-file: output/htmlpage.log
output-file: output/htmpdoctec.html
template: /home/vscode/hwo-academicTempl/templates/html-uikit.template  # html-uikit.template | html-uikit.template
to: html

