# input-files: [presentation.md]
log-file: output/htmlpage.log
output-file: output/htmpropuessta.html
template: /workspaces/hwo-academicTempl/html-uikit.template  # html-uikit.template | html-uikit.template
to: html

