---
codeBlockCaptions: True
figureTitle: |
  Figura #
lofTitle: |
  ## Lista de Figuras
lotTitle: |
  ## Lista de Tablas
lolTitle: |
  ## Listas del Documento
tableTemplate: |
  *$$tableTitle$$ $$i$$*$$titleDelim$$ $$t$$
autoSectionLabels: True
---
