input-file: output/manuscript.md
log-file: output/pdfdoctec.log
output-file: output/pdfdoctec-${TRIGGERING_SHA_7}.pdf
pdf-engine: pdflatex #tectonic wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, pdfroff, context
to: pdf
toc-depth: 2
