input-file: output/manuscript.md
log-file: output/pdfdoctec.log
output-file: output/pdfdoctec.pdf
pdf-engine: pdflatex #wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, pdfroff, context
to: pdf
toc-depth: 2
