input-file: output/manuscript.md
template: /Users/hwong23/git/devdocs/hwo-academicTempl/templates/eisvogel.tex
log-file: output/texdoctec.log
output-file: output/texdoctec.tex
pdf-engine: tectonic # wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, pdfroff, context, tectonic
to: latex
toc-depth: 2
