name: MkPandoc

on: workflow_dispatch

jobs:
  tx_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
          echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
          echo "COMPILATION_DATE=$(date +'%d %b %Y')" >> $GITHUB_ENV
          echo "TRIGGERING_SHA: $TRIGGERING_SHA"
      - uses: actions/checkout@v4
        name: checkout devocscontd
        with:
            repository: hwong23/devocs-contd
            ref: ${{github.ref}}
            path: devocs-contd
      - name: mensaje commit devocscontd
        run: |
          cd ${{github.WORKSPACE}}/devocs-contd
          echo "COMPILATION_MENSJ=$(git log --max-count=1 --format='.%h - Compilación para entrega: %s')" >> $GITHUB_ENV
          echo "COMPILATION_MENSJ: $COMPILATION_MENSJ"
      - uses: actions/checkout@v4
        name: checkout hwo-academicTempl
        with:
            repository: hwong23/hwo-academicTempl
            ref: ${{github.ref}}
            path: hwo-academicTempl
      - name: mv devocscontd hwo-academicTempl
        run: |
          mv ${{github.WORKSPACE}}/devocs-contd ~/devocs-contd
          mv ${{github.WORKSPACE}}/hwo-academicTempl ~/hwo-academicTempl
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install pandoc and pandoc-crossref
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb
          sudo dpkg -i pandoc-3.1.8-1-amd64.deb
          rm pandoc-3.1.8-1-amd64.deb
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.17.0/pandoc-crossref-Linux.tar.xz
          tar -xvf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /usr/bin
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: 2.17
      - name: Make doctec #configurar-flujo
        run: |
          export APPIMAGE_EXTRACT_AND_RUN=1
          CONTD=~/devocs-contd/contd
          make doctec CONTD=$CONTD  #configurar-flujo
      - name: Run Tectonic
        run: | 
          ls ./output/images
          tectonic ./output/*.tex
      - name: Upload pdf/artifact
        uses: actions/upload-artifact@v4
        with:
          name: output artifacts
          path: |
            output/*.pdf
            output/*.docx
            output/*.pptx
            output/*.html
            output/*.tex
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: '1. Compilación para entrega: 1.${{ env.COMPILATION_MENSJ }}'
