name: MkPandoc

on: workflow_dispatch

jobs:
  tx_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout devocscontd
        with:
            repository: hwong23/devocs-contd
            path: devocs-contd
      - uses: actions/checkout@v4
      - name: Install pandoc and pandoc-crossref
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb
          sudo dpkg -i pandoc-3.1.8-1-amd64.deb
          rm pandoc-3.1.8-1-amd64.deb
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.17.0/pandoc-crossref-Linux.tar.xz
          tar -xvf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /usr/bin
          ls ${{ github.WORKSPACE }}/devocs-contd

      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: 2.17
      - name: Make propuesta
        run: |
          export APPIMAGE_EXTRACT_AND_RUN=1
          make propuesta
      - name: Run Tectonic
        run: tectonic output/*.tex
      - name: Upload pdf/artifact
        uses: actions/upload-artifact@v4
        with:
          name: output artifacts
          path: |
            output/*.pdf
            output/*.docx
            output/*.pptx
            output/*.html
            output/*.tex
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'GitHub action artefacts added'
